// Generated by CoffeeScript 1.12.6
(function() {
  var Main, layout;

  Main = (function() {
    function Main() {
      this.initBackground();
      this.initTop();
    }

    Main.prototype.initTop = function() {
      var counter, interval_count, interval_sec;
      interval_sec = 0.5;
      interval_count = 5;
      counter = 0;
      return setInterval((function(_this) {
        return function() {
          counter += 1;
          if (counter % interval_count === 0) {
            return $('#top img.scroll_down').css('opacity', '0');
          } else {
            return $('#top img.scroll_down').css('opacity', '1');
          }
        };
      })(this), interval_sec * 1000 / interval_count);
    };

    Main.prototype.initBackground = function() {
      var rotation;
      rotation = 0;
      return setInterval((function(_this) {
        return function() {
          rotation += 1;
          return $('#base img.rolling').css('transform', "rotate(" + rotation + "deg)");
        };
      })(this), 33);
    };

    return Main;

  })();

  layout = function() {
    var height, max_width, width;
    width = $(window).width();
    height = $(window).height();
    max_width = height * 0.7;
    if (width > max_width) {
      $('#container').width(max_width);
      $('#base').width(max_width);
      $('#container').css('left', (width - max_width) / 2);
      return $('#base').css('left', (width - max_width) / 2);
    }
  };

  $(function() {
    new Main;
    layout();
    return $(window).resize(function() {
      return layout();
    });
  });

  window.onload = function() {
    return $('#container').css('opacity', 1.0);
  };

}).call(this);
